# Generated by Django 3.2.14 on 2024-05-14 11:31

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "db_table": "groups",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="teacher",
            name="ext_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата увольнения"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Штатный"),
                    (2, "Совместитель"),
                    (3, "Выбыл"),
                    (4, "Почасовик"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="uuid",
            field=models.UUIDField(
                default="8759ffab-7a47-126f-3cab-ca3ae264d20c",
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="oauth.group",
                verbose_name="Группа",
            ),
        ),
        migrations.CreateModel(
            name="GroupTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="oauth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа Translation",
                "db_table": "groups_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
