# Generated by Django 3.2.14 on 2024-05-14 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0002_auto_20240514_1631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oauth.teacherlevel",
                verbose_name="Уровень",
            ),
        ),
    ]
