# Generated by Django 3.2.14 on 2024-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0003_alter_teacher_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
